# k8s/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chatbot-backend-pdb
  namespace: chatbot
  labels:
    app: chatbot-backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chatbot-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: chatbot-frontend-pdb
  namespace: chatbot
  labels:
    app: chatbot-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: chatbot-frontend
