apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: chatbot-base

resources:
  - namespace.yaml
  - service-accounts.yaml
  - backend-deploy.yaml
  - backend-svc.yaml
  - frontend-deploy.yaml
  - frontend-svc.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: chatbot
  app.kubernetes.io/managed-by: kustomize

images:
  - name: "<ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/chatbot-backend"
    newTag: "latest"
  - name: "<ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/chatbot-frontend"
    newTag: "latest"
